//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veiculos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int Id_Historico { get; set; }
        public System.DateTime DataRegistro { get; set; }
        public double Valor { get; set; }
        public int Id_Carro { get; set; }
        public string Manutencao { get; set; }
    
        public virtual Carro Carro { get; set; }
    }
}
